GET https://jsonplaceholder.typicode.com/posts/1

POST https://jsonplaceholder.typicode.com/posts
Content-Type: application/json

{
  "title": "Mi primer post",
  "body": "Este es el contenido del post.",
  "userId": 1
}